[versions]
agp = "9.0.0"
commonsCollections4 = "4.5.0"
commonsLang3 = "3.20.0"
javafaker = "1.0.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lombokVersion = "1.18.42"
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragment = "2.9.7"
navigationUi = "2.9.7"

[libraries]
commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "commonsCollections4" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
javafaker = { module = "com.github.javafaker:javafaker", version.ref = "javafaker" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
projectlombok-lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

